<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup Label="Test Packages">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="Testcontainers.RabbitMq" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\src\Host\EDCL.Api\EDCL.Api.csproj" />
  </ItemGroup>

</Project>