namespace EDCL.IdcsSeeder;

public static class LogisticPartnerData
{
    public static readonly (string Code, string Name)[] Data = new[]
    {
        ("YAI", "YASUNAGA INDONESIA"),
        ("ALS", "Armas Logistic Service"),
        ("NPC", "NIPSEA PAINT CHEMICA"),
        ("KPI", "KANSAI PAINT IND"),
        ("TOL", "TOLL"),
        ("ACG", "ACL GASKET FIS"),
        ("ACB", "ACL BEARING FIS"),
        ("GAB", "GABC"),
        ("VEL", "VELASTO INDONESIA"),
        ("MCP", "MCPHERSONS"),
        ("IR3", "IRC INOAC INDONESIA"),
        ("IR1", "INOAC RUB INDONESIA"),
        ("WLD", "WELDING STRI"),
        ("ND2", "DENSO INDONESIA CORP"),
        ("KGI", "KGD INDONESIA INC."),
        ("TDW", "TRI DHARMA WISESA"),
        ("IGP", "INTI GANDA PERDANA"),
        ("WEP", "WAHANA EKA PARAMITRA"),
        ("SGT", "SUGITY CREATIVES"),
        ("GKD", "GEMALA KEMPA DAYA"),
        ("AOP", "ASTRA OTOPARTS"),
        ("FNM", "ASTRA OTOPARTS UNIT"),
        ("NTC", "NUSA TOYOTETSU CORP."),
        ("P3T", "PAMINDO TIGA T."),
        ("AMA", "ASALTA MANDIRI AGUNG"),
        ("MES", "METINDO ERA SAKTI"),
        ("GSS", "GUNA SENAPUTRA SEJAH"),
        ("ATI", "AISIN TAKAOKA I"),
        ("NHC", "NUSAHADI CITRAHARMON"),
        ("KFN", "KOMPONEN FUTABA NUSA"),
        ("ABA", "ABADI BARINDO AUTOTE"),
        ("3MI", "3 M INDONESIA"),
        ("AII", "AISIN INDONESIA"),
        ("AEF", "ANEKA ELEKTRINDO"),
        ("AKU", "ANEKA KOMKAR UTAMA"),
        ("AGP", "ARGAPURA TRADING COM"),
        ("ASJ", "ASAHIMAS FLAT GLASS"),
        ("BAK", "BAKRIE TOSANJAYA"),
        ("BDI", "BANDO INDONESIA"),
        ("BSI", "BRIDGESTONE TIRE IND"),
        ("SIN", "CATURINDO AGUNGJAYA"),
        ("CHI", "CHUHATSU INDONESIA"),
        ("DWA", "DASA WINDU AGUNG"),
        ("NDI", "DENSO INDONESIA CORP"),
        ("CKI", "DINAHETI MOTOR INDUS"),
        ("ENI", "ENKEI - INDONESIA"),
        ("GSB", "G.S. BATTERY"),
        ("GTI", "GAJAH TUNGGAL TBK"),
        ("GMU", "GARUDA METAL UTAMA"),
        ("GYI", "OD YEAR INDONESIA"),
        ("LIP", "HI-LEX INDONESIA"),
        ("ICH", "ICHIKOH IND"),
        ("DCT", "INDOCIPTA HASTA PERK"),
        ("IKP", "INDOKARLO PERKASA"),
        ("IDS", "INDOSAFETY SENTOSA I"),
        ("ANI", "AISAN NASMOCO I"),
        ("ACD", "ASNO HORIE INDONESIA"),
        ("ATL", "AUTOLIV INDONESIA"),
        ("ATC", "AUTOTECH INDONESIA"),
        ("INK", "INKOASKU"),
        ("DCI", "DAIKIN CLUTCH INDONE"),
        ("JBI", "JIBUHIN BAKRIE INDON"),
        ("KYB", "KAYABA INDONESIA"),
        ("FKI", "FUKOKU INDONESIA"),
        ("HIM", "HINO INDONESIA MANUF"),
        ("KSB", "KSB INDONESIA"),
        ("TTK", "TOYOTA TSUSHO KIMURA"),
        ("KBI", "KYORAKU B.IND"),
        ("PCD", "TMMIN PCD STRI"),
        ("MEI", "MEIWA INDONESIA"),
        ("MTM", "MENARA TERUS MAKMUR"),
        ("MAW", "MESHINDO ALLOY WHEEL"),
        ("SNH", "SANOH INDONESIA"),
        ("SEI", "SEIWA INDONESIA"),
        ("THO", "TAIHO NUSANTARA"),
        ("MTW", "MUARA TEWE SPRING"),
        ("STP", "STAMPING STRII"),
        ("NGK", "NGK BUSI"),
        ("ALU", "ALUK"),
        ("BIL", "BILS DE ROO"),
        ("EXC", "EXEL"),
        ("FMS", "FRANS MAAS"),
        ("GEF", "GEFCO"),
        ("LPC", "LPC"),
        ("SEA", "SEA"),
        ("TFE", "TRANSFREIGHT EUROPE"),
        ("UCI", "UCIL"),
        ("5074", "NICHIAS SUNI JAYA"),
        ("OTI", "OTICS INDONESIA"),
        ("PRI", "PAKARTI RIKEN INDONE"),
        ("PKO", "PAKOAKUINA"),
        ("PLD", "PALINGDA NASIONAL"),
        ("PTI", "PUTRA INDONESIA"),
        ("SSO", "SEKISO INDUSTRIES IN"),
        ("SII", "SEKISO INDUSTRIES IN"),
        ("SWU", "SINAR WIRA UTAMA"),
        ("SWS", "SUMI INDO WIRING SYS"),
        ("SRO", "SUMI RUBBER INDONESI"),
        ("YBI", "YUASA BATERY IND."),
        ("GSA", "GEMA SUARA ADHITAMA"),
        ("WKA", "WIJAYA KARYA"),
        ("TTI", "TOYOTA TSUSHO INDONE"),
        ("SIB", "SINAR BERLIAN CHEMIN"),
        ("TGS", "TOYODA  SEI SAFETY"),
        ("NTP", "PT NT PISTON RING IN"),
        ("NSB", "PT NSK BEARINGS"),
        ("STG", "SARI TAKAGI E.P"),
        ("AFI", "AICHI FORGING IND"),
        ("ADV", "ADVICS INDONESIA"),
        ("DMI", "PT EDS MFG INDONESIA"),
        ("SOL", "MULTI CELCOM"),
        ("FNI", "FEDERAL NITTAN INDUS"),
        ("DLY", "DELLOYD INDONESIA"),
        ("NIC", "NAMICOH INDONESIA"),
        ("SJI", "SAKURA JAVAINDONESIA"),
        ("CMI", "CENTRAL MTR WHEEL IN"),
        ("AD2", "ASTRA DAIHATSU MTR 2"),
        ("ND3", "DENSO INDONESIA CORP"),
        ("WHA", "SPECIAL"),
        ("IBU", "INDOLOK BAKTI UTAMA"),
        ("JVC", "JAYA VICTORI CEMERLA"),
        ("NMI", "NITTO MATERIALS IND."),
        ("CHA", "CHALMERS"),
        ("MHG", "MHG"),
        ("TTA", "TTA TRANSPORT"),
        ("EMA", "EDS MANUFACTURING IN"),
        ("ASI", "AUTOCOMP SYSTEM INDO"),
        ("KNK", "OZPRESS"),
        ("MGL", "MULIA GLASS"),
        ("EMP", "EMPIRE RUBBER"),
        ("OCI", "OCIA"),
        ("CHY", "CHYIODA"),
        ("NHK", "NHK GASKET"),
        ("NHK", "ASTRA NIPPON G. IND."),
        ("TLI", "TRANSYSTEM LOGISTICS"),
        ("TTN", "Toyota Tsusho Nusa Transport"),
        ("ASM", "ASMO"),
        ("KLI", "K-LINE"),
        ("ABC", "ABC BO R"),
        ("ZZZ", "ZZZ"),
        ("TTL", "TTLC LOG PARTNER"),
        ("NYK", "NYK PUNINAR"),
        ("MML", "Mandiri Mitra Logistik"),
        ("AD1", "ASTRA DAIHATSU MTR 1"),
        ("DSU", "DUMAS SAKTI UTAMA"),
        ("PYL", "Puninar Yusen Logistic Indones"),
        ("MKS", "MULTI KARYA"),
        ("TSC", "TAKAGI SARI MULTI UTAMA"),
        ("0003", "SUGITY CREATIVES"),
        ("0007", "ASTRA OTOPARTS Tbk"),
        ("5002", "ASALTA MANDIRI AGUNG"),
        ("5011", "AISIN INDONESIA"),
        ("5015", "ASAHIMAS FLAT GLASS"),
        ("5018", "BRIDGESTONE TIRE INDONESIA"),
        ("5007", "SARI TAKAGI ELOK PRODUK"),
        ("5009", "TOYOTA BOSHOKU INDONESIA"),
        ("5021", "DASA WINDU AGUNG"),
        ("5032", "HI-LEX INDONESIA"),
        ("5033", "ICHIKOH INDONESIA"),
        ("5039", "ASNO HORIE INDONESIA"),
        ("5049", "FUKOKU INDONESIA"),
        ("5091", "PT. INOAC POLYTECHNO INDONESIA"),
        ("5142", "AICHI FORGING INDONESIA"),
        ("5155", "TOYODA  SEI SAFETY SYSTEMS IND"),
        ("5226", "PT. SANKO  SEI TECHNOLOGY INDONESIA"),
        ("5301", "PT. INDONESIA KOITO"),
        ("5302", "PT. JTEKT INDONESIA"),
        ("5304", "PT. TOKAI RIKA INDONESIA"),
        ("5327", "PT.SUGIURA INDONESIA"),
        ("5328", "PT. MEIDOH INDONESIA"),
        ("5367", "PT. NIFCO INDONESIA"),
        ("5368", "PT. MTAT INDONESIA"),
        ("0001", "Inti Ganda Perdana, PT"),
        ("0005", "Astra Daihatsu Motor, PT"),
        ("0008", "Federal Nusa Metal,  PT"),
        ("0048", "Patec Presisi Engineering. PT"),
        ("5000", "Nusa Toyotetsu Corporation, PT"),
        ("5003", "Metindo Era Sakti, PT"),
        ("5004", "Guna Senaputra Sejahtera, PT"),
        ("5005", "AT Indonesia,PT"),
        ("5006", "Nusahadi Citrahamonis, PT"),
        ("5008", "Komponen Futaba Nusapersada, PT"),
        ("5020", "Chuhatsu Indonesia, PT"),
        ("5022", "Denso Sales Indonesia, PT"),
        ("5024", "Autocomp Systems  Indonesia, PT"),
        ("5182", "Astra Juoku Indonesia, PT"),
        ("5035", "Indokarlo Perkasa, PT"),
        ("5038", "Aisan Nasmoco Industri, PT"),
        ("5040", "Autoliv Indonesia, PT"),
        ("5048", "Kayaba Indonesia, PT"),
        ("5054", "IRC Inoac  Indonesia, PT [Rb]"),
        ("5059", "NSK Indonesia, PT"),
        ("5065", "Sanoh Indonesia, PT"),
        ("5067", "Taiho Nusantara, PT"),
        ("5075", "Otics Indonesia, PT"),
        ("5077", "Pakoakuina, PT"),
        ("5083", "Sumi Rubber Indonesia, PT"),
        ("5108", "Automotive Fasterners Aoyama Indonesia, PT"),
        ("5143", "Central Motor Wheel Indonesia, PT"),
        ("5145", "Federal Nittan Industries, PT"),
        ("5151", "Sakura Java Indonesia, PT"),
        ("5156", "Yasunaga Indonesia, PT"),
        ("5159", "Advics Indonesia, PT"),
        ("5178", "Ochiai Menara Indonesia, PT"),
        ("5228", "Setia Guna Sejati, PT"),
        ("5364", "Dharma Control Cable, PT"),
        ("0008", "Federal Nusa Metal,  PT"),
        ("5375", "PT. NACHI INDONESIA"),
        ("5376", "Futaba Indonesia, PT"),
        ("5875", "Citra Nugrah Karya"),
        ("5010", "3M Indonesia, PT"),
        ("5159", "Advics Indonesia, PT"),
        ("5202", "Adyawinsa Dinamika, PT"),
        ("5142", "Aichi Forging Indonesia, PT"),
        ("5038", "Aisan Nasmoco Industri, PT"),
        ("5011", "Aisin Indonesia,  PT"),
        ("5200", "APM Armada Autopart, PT"),
        ("5014", "Argapura Trading Co., PT"),
        ("5207", "Armstrong Industri Indonesia, PT"),
        ("5015", "Asahimas Flat Glass Tbk, PT"),
        ("5002", "Asalta Mandiri Agung, PT"),
        ("5039", "Asno Horie Indonesia, PT"),
        ("0005", "Astra Daihatsu Motor, PT"),
        ("5182", "Astra Juoku Indonesia, PT"),
        ("5073", "Astra Nippon Gasket Indonesia, PT"),
        ("0007", "Astra Otopart Tbk., PT (div Plastic)"),
        ("5005", "AT Indonesia,PT"),
        ("5024", "Autocomp Systems  Indonesia, PT"),
        ("5040", "Autoliv Indonesia, PT"),
        ("5108", "Automotive Fasterners Aoyama Indonesia, PT"),
        ("5012", "Anugrah Valova Electrindo, PT"),
        ("5017", "Bando Indonesia, PT"),
        ("5018", "Bridgestone Tire Indonesia, PT"),
        ("5143", "Central Motor Wheel Indonesia, PT"),
        ("5175", "Chiyoda Integre Indonesia, PT"),
        ("5020", "Chuhatsu Indonesia, PT"),
        ("5875", "Citra Nugrah Karya"),
        ("5918", "Daido Indonesia Manufacturing, PT"),
        ("5350", "Daikyo Nishikawa Tenma Indonesia, PT"),
        ("5021", "Dasa Windu Agung, PT"),
        ("5022", "Denso Sales Indonesia, PT"),
        ("5144", "Murakami Dellyd Indonesia, PT"),
        ("5364", "Dharma Control Cable, PT"),
        ("5025", "Enkei Indonesia, PT"),
        ("5212", "Excel Indonesia,PT"),
        ("5145", "Federal Nittan Industries, PT"),
        ("0008", "Federal Nusa Metal,  PT"),
        ("5049", "Fukoku Tokai Rubber Indonesia, PT"),
        ("5376", "Futaba Indonesia, PT"),
        ("5028", "Garuda Metal Utama, PT"),
        ("5029", "Garuda Metalindo, PT"),
        ("5026", "GS Battery"),
        ("5308", "GS Electech Indonesia, PT"),
        ("5004", "Guna Senaputra Sejahtera, PT"),
        ("5032", "Hilex Indonesia, PT"),
        ("5033", "Ichikoh  Indonesia, PT"),
        ("5034", "Indocipta Hasta Perkasa, PT"),
        ("5035", "Indokarlo Perkasa, PT"),
        ("5301", "Indonesia Koito, PT"),
        ("5055", "Indonesia Stanley Electric, PT"),
        ("5346", "Indonesia Thai Summit, PT"),
        ("5243", "Ingress Malindo Ventures, PT"),
        ("5044", "Inkoasku, PT"),
        ("5147", "Inoac TG Indonesia, PT"),
        ("5091", "Inoac Polytechno Indonesia, PT [PU]"),
        ("5054", "IRC Inoac  Indonesia, PT [Rb]"),
        ("0001", "Inti Ganda Perdana, PT"),
        ("5302", "Jtekt Indonesia, PT"),
        ("5166", "Jaya Victori Cemerlang, PT"),
        ("5048", "Kayaba Indonesia, PT"),
        ("5008", "Komponen Futaba Nusapersada, PT"),
        ("5219", "Kotobukiya Indo Classic Industries Pt"),
        ("5336", "Kyokuyo Industrial Indonesia, PT"),
        ("5058", "Kyoraku Blow Molding Indonesia, PT"),
        ("5328", "Meidoh Indonesia, PT"),
        ("0047", "Mekar Armada jaya, PT"),
        ("5062", "Menara Terus Makmur, PT"),
        ("5064", "Meshindo Alloy Wheel, PT"),
        ("5003", "Metindo Era Sakti, PT"),
        ("5368", "Tsuda & Manoh Indonesia, PT"),
        ("5137", "Multi Karya Sinar Dinamika, PT"),
        ("5150", "Namicoh Indonesia Component,PT"),
        ("5367", "Nifco Indonesia, PT"),
        ("5789", "Nitto Materials Indonesia, PT"),
        ("5246", "NOK Indonesia, PT"),
        ("5059", "NSK Indonesia, PT"),
        ("5060", "NT Piston Ring Indonesia, PT"),
        ("5000", "Nusa Toyotetsu Corporation, PT"),
        ("5006", "Nusahadi Citrahamonis, PT"),
        ("5178", "Ochiai Menara Indonesia, PT"),
        ("5075", "Otics Indonesia, PT"),
        ("5077", "Pakoakuina, PT"),
        ("5079", "Putra Indonesia, PT"),
        ("0048", "Patec Presisi Engineering. PT"),
        ("5112", "Robert Bosch Indonesia, PT"),
        ("5151", "Sakura Java Indonesia, PT"),
        ("5226", "Sanko  sei Indonesia, PT"),
        ("5065", "Sanoh Indonesia, PT"),
        ("5007", "Sari Takagi Elok Produk, PT"),
        ("5066", "Seiwa Indonesia, PT"),
        ("5080", "Sekiso Industries Indonesia, PT"),
        ("5228", "Setia Guna Sejati, PT"),
        ("5311", "Shiroki Indonesia, PT"),
        ("5386", "Shinto Kogyo Indonesia, PT"),
        ("0003", "Sugity Creatives, PT"),
        ("5327", "Sugiura Indonesia, PT"),
        ("5082", "Sumi Indo Wiring System, PT"),
        ("5083", "Sumi Rubber Indonesia, PT"),
        ("5067", "Taiho Nusantara, PT"),
        ("5238", "Takagi Sari Multi Utama , PT"),
        ("5303", "Takata Automotive Safety System Indonesia, PT"),
        ("5304", "Tokai Rika Indonesia, PT"),
        ("5365", "Tokai Rubber Indonesia, PT"),
        ("5366", "Tokai Rubber Auto Hose Indonesia, PT"),
        ("5155", "Toyoda  sei Safety Systems Ind., PT"),
        ("5941", "Toyo Denso Indonesia, PT"),
        ("5009", "Toyota Boshoku Indonesia, PT"),
        ("5162", "Toyota Tsusho Indonesia, PT"),
        ("5317", "TPR Sales Indonesia, PT"),
        ("5359", "Tuffindo Nittoku Autoneum, PT"),
        ("5156", "Yasunaga Indonesia, PT"),
        ("5387", "Yohzu Somic Indonesia, PT"),
        ("5335", "DINAR MAKMUR PT."),
        ("5348", "KOJIMA AUTO TECHNOLOGY INDONESIA PT."),
        ("5396", "ARAI RUBBER SEAL INDONESIA PT."),
        ("5347", "FURUKAWA PERMINTEX AUTOPARTS INDONESIA PT."),
        ("5287", "CATALER INDONESIA PT."),
        ("5390", "PT. ASANO GEAR INDONESIA"),
        ("5375", "PT. NACHI INDONESIA"),
        ("5347", "FURUKAWA PERMINTEX AUTOPARTS INDONESIA PT."),
        ("5300", "PT. TOKAI RIKA SAFETY INDONESIA"),
        ("5247", "PT.ITOKIN INDONESIA"),
        ("5357", "PT. TSUCHIYA INDONESIA"),
        ("5358", "PT. LA VIDA HERCULON"),
        ("5242", "DHARMA POLI METAL"),
        ("5248", "PT.ART PISTON INDONESIA"),
        ("5333", "HOWA INDONESIA PT."),
        ("5388", "PT. MITSUBA INDONESIA PIPE PARTS"),
        ("5274", "PT.SUMIDEN SINTERED COMPONENT INDONESIA"),
        ("DUN", "Sumi Rubber Indonesia"),
        ("SYN", "Syncrum Logistics"),
        ("SGL", "Sumisho Global Logistics"),
        ("PTE", "PTE"),
        ("5337", "FUJITSU TEN AVE INDONESIA PT."),
        ("5263", "PT.DIAMOND ELECTRIC INDONESIA"),
        ("5345", "NISHIKAWA KARYA INDONESIA"),
        ("5319", "Fuji Kinzoku Indonesia, PT"),
        ("5320", "Fine Sinter Indonesia, PT"),
        ("HKR", "Hikari Logistics"),
        ("5286", "UYEMURA INDONESIA, PT"),
        ("5030", "GEMASUARA ADHITAMA, PT"),
        ("5307", "PT. SETIA GUNA SEJATI"),
        ("5349", "SAKAE RIKEN INDONESIA PT."),
        ("5433", "PT.KANEMITSU SGS INDONESIA"),
        ("5157", "DAIDO METAL INDONESIA"),
        ("DNX", "Dunia Express"),
        ("TBI", "TBINA"),
        ("BAI", "Bridgestone Astra Indonesia"),
        ("GML", "Garuda Metalindo"),
        ("NSJ", "Nichias Suni Jaya"),
        ("UNI", "Unicraft Nagura Indonesia"),
        ("KOI", "INDONESIA KOITO"),
        ("TRC", "TRICOO"),
        ("ADM", "Astra Daihatsu Motor"),
        ("AGR", "Agung Raya Logistik"),
        ("AJL", "Agung Jasa Logistik"),
        ("5513", "PT.JOYSON SAFETY SYSTEMS INDONESIA"),
        ("5316", "PT. BRIDGESTONE ASTRA INDONESIA"),
        ("5027", "PT.GAJAH TUNGGAL Tbk"),
        ("5453", "PT.VELASTO INDONESIA"),
        ("5498", "PT.AUTO PLASTIK INDONESIA"),
        ("5105", "PT. MINDA ASEAN AUTOMOTIVE"),
        ("5545", "PT. NOK INDONESIA SALES"),
        ("5490", "PT. DENSO TEN AVE INDONESIA"),
        ("NSI", "Nissho Solution Indonesia"),
    };
}
