<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\EDCL.Shared.Kernel\EDCL.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\Shared\EDCL.Shared.Infrastructure\EDCL.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
