<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup Label="NuGet Packages">
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\EDCL.Shared.Kernel\EDCL.Shared.Kernel.csproj" />
    <ProjectReference Include="..\EDCL.Shared.Infrastructure\EDCL.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
